# Ask user for the character of the eyes
print("What character should beep's eyes have?")
# Create variable and read user input
s = input()
# Display beep with the character inputed by the user
print("    ###########")
print("   #           #")
print("  ##  ### ###  ##")
print("  ##  #{}# #{}#  ##".format(s,s))
print("  ##  ### ###  ##")
print("  ##           ##")
print("   #   ###      #")
print("    ###########")
print("       #####")
print("   #############")
print("  #             #")
print("  ###         ###")
print("  #  #       #  #")
print("  ###         ###")
print("  #             #")
print("  #             #")
print("  #             #")
print("   #           #")
print("    ###########")
print("         #  ")